version: "3.4"

services:
  plaguposter_postgres:
    image: postgres:15.4-bullseye
    container_name: "plaguposter_postgres"
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    volumes:
      - "./db/:/var/lib/postgresql/data"
  plaguposter:
    image: insanusmokrassar/plaguposter:latest
    container_name: "plaguposter"
    restart: "unless-stopped"
    volumes:
      - "./config.json:/config.json"
    depends_on:
      - "plaguposter_postgres"
    links:
      - "plaguposter_postgres:postgres"
